name: Deploy app
on:
  push:
    branches:
      - main
env:
  SOURCE_REPO: https://github.com/AbhishekKadam11/shopifyEnv/tree/main/newTechFrontend
  AUTOMATIC_MONITOR: true
  FILES: "*.toml"
  FILES_NEW: "*.toml"
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX:  "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
  THE_SERVER: ${{ github.server_url }}
  PATH_SOURCE_CHECKOUT: newTechShopify
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Commit
        run: |
            git config user.name "$USERNAME"
            git config user.email "$USERNAME@$ADDRESS_SUFFIX"
            git add $FILES_NEW
            git commit -m "Pulled files from $THE_SERVER/$SOURCE_REPO."
      - name: Install npm dependencies
        run: npm install
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"