name: Deploy app
on:
  push:
    branches:
      - main
env:
  SOURCE_REPO: AbhishekKadam11/shopifyEnv
  SOURCE_BRANCH: main
  AUTOMATIC_MONITOR: true
  FILES: shopify.theme.toml
  FILES_NEW: shopify.theme.toml
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX:  "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
  THE_SERVER: ${{ github.server_url }}
  PRINT_PATH: ${{ github.workspace }}
  PATH_SOURCE_CHECKOUT: newTechShopify/newTechShopify/shopifyEnv
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Checkout shopify env repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ env.SOURCE_BRANCH }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}
          token: ${{ secrets.ENV_PRIVATE_ACCESS_TOKEN }}
      - name: Copy file to current repository
        run: |
          echo ${{ github.workspace }}
          cd $PATH_SOURCE_CHECKOUT
          cp -u $FILES_NEW ../
          cd ..
      - name: Install npm dependencies
        run: npm install
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"