name: Deploy Country Specific Theme

on:
  workflow_dispatch:
    inputs:
      langSelection:
        type: choice
        description: 'Language Selecion'     
        required: true
        default: 'en'
        options: 
        - en
        - de
        - jp
      tags:
        description: 'Test release tags'
env:
  STORE_SELECTED: ''

jobs:
  deploy:
    environment: deployment
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - if: github.event.inputs.langSelection == 'de'
        name: Copy templates and language locals
        run: |
          echo ${{ github.workspace }}
          echo "STORE_SELECTED=${{github.event.inputs.langSelection}}" >> $GITHUB_ENV
          echo " STORE_SELECTED "
          cp -r ./deployment/${{github.event.inputs.langSelection}}/locals/* ./locals
          cp -r ./deployment/${{github.event.inputs.langSelection}}/templates/* ./templates
          ls

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3.66.1 @shopify/theme 

      - name: Install gem bundler
        run: sudo gem install bundler

      # - name: Pull JSON files from live theme
      #   env:
      #     SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_STORE_URL }}'
      #     SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}
      #     SHOPIFY_CLI_TTY: 0
      #     SHOPIFY_FLAG_FORCE: 1
      #   run: |
      #     # Create a temporary directory for JSON files
      #     mkdir temp_json
      #     # Pull all JSON files to the temporary directory
      #     shopify theme pull --theme=${{ secrets.SHOPIFY_THEME_ID }} --only '*.json' --path temp_json
      #     # Compare and copy newer files
      #     for file in temp_json/**/*.json; do
      #       rel_path=${file#temp_json/}
      #       if [ ! -f "$rel_path" ] || [ "$file" -nt "$rel_path" ]; then
      #         mkdir -p $(dirname "$rel_path")
      #         cp "$file" "$rel_path"
      #         echo "Updated: $rel_path"
      #       fi
      #     done
      #     # Clean up
      #     rm -rf temp_json

      - name: Install vite
        run: npm install vite 
      
      - name: Run vite build
        run: npm run vite:build 

      - name: Upload theme
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_STORE_URL }}'
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_CLI_TTY: 0
          SHOPIFY_FLAG_FORCE: 1
        run: |
          shopify theme push \
            --json \
            --theme ${{ secrets.SHOPIFY_THEME_ID }} \
            --store ${{ secrets.SHOPIFY_STORE_URL }} \
            --password ${{ secrets.SHOPIFY_PASSWORD }} \
            --unpublished