name: Deploy Staging Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: deployment
    name: Deploy Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v3
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.2.2
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ./
        # with:
        #   args: --ignored-file=config/settings_data.json --ignored-file=locales/*