name: Deploy Staging Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # setup python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: python my_script.py
      # deploy shopify theme
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ./
        # with:
        #   args: --ignored-file=config/settings_data.json --ignored-file=locales/*