name: Deploy Staging Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: deployment
    name: Deploy Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v3
      - name: echo env var
        run: |
           echo ${{ secrets.SHOPIFY_STORE_URL }} | sed 's/./& /g'
           echo ${{ secrets.SHOPIFY_THEME_ID }} | sed 's/./& /g'
      # deploy shopify theme
      - name: Shopify Theme Actions
        uses: matthew-petrie/shopify-theme-actions@1.2.2
        with:
          ACTION: "DEPLOY"
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_THEME_DIRECTORY: "./dist"
          SHOPIFY_ALLOW_LIVE_THEME_DEPLOYMENT: true
        # with:
        #   args: --ignored-file=config/settings_data.json --ignored-file=locales/*