name: Deploy Staging Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: deployment
    name: Deploy Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v3
      - name: echo env var
        run: |
           echo ${{ secrets.SHOPIFY_STORE_URL }} | sed 's/./& /g'
           echo ${{ secrets.SHOPIFY_THEME_ID }} | sed 's/./& /g'
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.2.2
        env:
          SHOPIFY_PASSWORD: shptka_3eeea5663394b88ce367b1fe0b3fd2f1
          SHOPIFY_STORE_URL: quickstart-8735ef1f.myshopify.com
          SHOPIFY_THEME_ID: 134596263989
          THEME_PATH: ./
        # with:
        #   args: --ignored-file=config/settings_data.json --ignored-file=locales/*