name: Deploy Staging Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          shopify theme push \
            --json \
            --theme newTech \
            --store ${{ secrets.SHOPIFY_STORE_URL }} \
            --password ${{ secrets.SHOPIFY_PASSWORD }}